# Generated by Django 5.0.4 on 2024-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='valor',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
