# Generated by Django 5.0.4 on 2024-07-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carrito_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
